---
title: "Lab 4"
output: 
  html_document:
    theme: united
    toc: yes
    toc_float:
      collapsed: true
editor_options: 
  chunk_output_type: console
---

## Chilean 1988 Survey Data

```{r echo=TRUE}
# load data
chile <- carData::Chile

# summary
summary(chile)
```

## Estimate model of support for SQ on age, population, income

```{r echo=TRUE}
m1 <- lm(statusquo ~ age + income + population, chile)
summary(m1)
```

These coefficients are really hard to interpret because of scaling issues. Let's rescale to something more reasonable.

```{r echo=TRUE}
# rescale vars
chile$age_10 <- chile$age / 10 # age in decades
chile$income_10K <- chile$income / 10000 # income in 10 thousands
chile$population_10K <- chile$population / 10000 # population in 10 thousands

# reestimate model
m1 <- lm(statusquo ~ age_10 + income_10K + population_10K, chile)
summary(m1)
```

## Reproduce sig tests by hand

```{r echo=TRUE}
# store betas
B <- coef(m1)

# calculate standard errors
se <- sqrt(diag(vcov(m1)))

# calculate t stats
t <- B / se

# calculate p values for 2-tailed
p <- ( 1 - pt(abs(t), df = m1$df.residual) ) * 2

# report neatly
round(cbind(Beta = B, se = se, t = t, p = p), 4)
```

## Confidence intervals

```{r echo=TRUE}
# using confint
confint(m1)
```

```{r echo=TRUE}
# reproduce by hand
cbind(
  B + qt(0.025, df = m1$df.residual) * se,
  B + qt(0.975, df = m1$df.residual) * se
)
```

```{r echo=TRUE}
# get fancy (and efficient) using apply
CIs <- sapply(c(0.025, 0.20, 0.80, 0.975), 
              function(x) B + qt(x, df = m1$df.residual) * se)
CIs
```

```{r echo=TRUE, fig.height=6}
# plot with "visually weighted" CIs
par(mar=c(5,4,1,1))
plot(1:3, B[2:4], pch=19, xlab="", ylab="marginal effect", 
     xlim=c(0.75, 3.25), ylim=c(-0.05, 0.15), axes=F)
axis(1, at=1:3, labels = c("Age (decades)", "Income (10Ks)", "Pop. (10Ks)"))
axis(2, at=seq(-0.05, 0.15, 0.05))
segments(1:3, CIs[2:4, 1], 1:3, CIs[2:4, 4], lwd=1, lty=1)
segments(1:3, CIs[2:4, 2], 1:3, CIs[2:4, 3], lwd=3, lty=1)
abline(h=0, lty=3)
box()
```

```{r echo=TRUE, warning=FALSE, message=FALSE}
# make table
m1_tab <- cbind(
  Var = c("Intercept","Age (decades)", "Income (10Ks)", "Pop. (10Ks)"),
  B = round(coef(m1), 3),
  se = round(sqrt(diag(vcov(m1))), 3),
  round(confint(m1), 3)
)

# packages needed for what is below
library(kableExtra)
library(dplyr)
library(knitr)

# create and print table
kable(m1_tab, row.names = F) %>%
  kable_classic(full_width = T, html_font = "Cambria") %>%
  add_footnote(
    c(
      "------",
      paste0("N = ", nrow(m1$model)), 
      paste0("adj. R2 = ", round(summary(m1)$adj.r.squared, 3)), 
      "Notes: DV is support for status quo, in SD units"
    ), 
    notation = "none"
  )
```

## Using `linearHypothesis` in `car` for tests

```{r echo=TRUE}
car::linearHypothesis(m1, "age_10 = 0")
car::linearHypothesis(m1, "age_10 = 0.05")
car::linearHypothesis(m1, c("age_10 - income_10K = 0"))
summary(lm(statusquo ~ age_10 + I(age_10 + income_10K) + population_10K, chile))
```













