---
title: "R Notebook"
output: html_notebook
---

N observations: students

block assignment

treatment assignment

outcome

ATE = E[Y1 - Y0]
= E[Y1] - E[Y(0)]

P[X=0]...

remember 
rep()
if you want it to repeat

X = rep(0:1, c(.4,.6)*N)

repeat 1 .6 of the time, 0 .4 percent of the time

question: to vary the percentage across samples to do power calculations

what change in order to change n across iterations

replace (.4,.6) with

(1-p, p)

so now X = re(0:1, c(1-p, p)*N)

in declare design to change the p we can use redesign

redesign(design, p=c(0.2,.04,0.6))

then can graph power for p is 0.2, 0.4, 0.6

can do this with different parts of the design to see what works best

how to check we did this right

we set the design
we know in expectation that .6, .75, .7, .8

we'd only saved success[i] (how many )

success[i] <- model$p.value <= 0.05

#init

n_untreated_undergrads_with_a[i] <- c()

n_untreated_undergrads_with_a[i] <- sum(matcha[matcha$grad ==0]$exam & matcha$treat ==0])

n_untreated_undergrads_with_a[i] <- sum(matcha[matcha$grad ==1]$exam)

should be
60 undergrads, half untreated, . . .
 100*0.4*0.5*0.6

sample size 100
40% undergrads
half are treated, half are untreated, among them 60% get an A





